//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NBA
{
    using System;
    using System.Collections.Generic;
    using System.Linq;

    public partial class Player
    {
        public int Experience
             => DateTime.Now.Year - this.JoinYear.Year;
        public decimal Salary
            => this.PlayerInTeams.FirstOrDefault()?.Salary ?? 0;
        public double PPG
            => this.PlayerStatistics.Any() ? this.PlayerStatistics.Average(x => x.Point) : 0;
        public double RPG
            => this.PlayerStatistics.Any() ? this.PlayerStatistics.Average(x => x.Rebound) : 0;
        public double APG
            => this.PlayerStatistics.Any() ? this.PlayerStatistics.Average(x => x.Assist) : 0;


    }
    public partial class Player
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Player()
        {
            this.MatchupLogs = new HashSet<MatchupLog>();
            this.MatchupLogs1 = new HashSet<MatchupLog>();
            this.PlayerInTeams = new HashSet<PlayerInTeam>();
            this.PlayerStatistics = new HashSet<PlayerStatistic>();
        }
    
        public int PlayerId { get; set; }
        public string Name { get; set; }
        public int PositionId { get; set; }
        public System.DateTime JoinYear { get; set; }
        public decimal Height { get; set; }
        public decimal Weight { get; set; }
        public System.DateTime DateOfBirth { get; set; }
        public string College { get; set; }
        public string CountryCode { get; set; }
        public string Img { get; set; }
        public byte[] Photo { get; set; }
        public bool IsRetirment { get; set; }
        public Nullable<System.DateTime> RetirmentTime { get; set; }
    
        public virtual Country Country { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MatchupLog> MatchupLogs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MatchupLog> MatchupLogs1 { get; set; }
        public virtual Position Position { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PlayerInTeam> PlayerInTeams { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PlayerStatistic> PlayerStatistics { get; set; }
    }
}
